### PR TITLE
[WIP] docs fixes

### PR DESCRIPTION
**Pull request by QuantumChemist**
some corrections, adjustments and fixes of the documentation
- [x] add more documentation on the choice of the fitting parameter for the phonon workflow. maybe, provide the Si choice as a default or explain how to chose it
- [x] add documentation on how to allow users to adapt VASP settings more easily

### CODE REVIEW

**Comment by QuantumChemist** [comment]
I accidentally closed this

**Comment by JaGeo** [comment]
Just reopen

**Comment by QuantumChemist** [comment]
> Just reopen

I can't because my fork is now detached as it's still private but I'm about to open a new PR.

**Comment by JaGeo** [comment]
Aaah. i see. Don't worry.

**Pull request closed without merging**
