### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by naik-aakash**

### CODE REVIEW

**Comment by JaGeo** [comment]
@naik-aakash maybe clean_dir for all tests? Still hanging in the rss part

**Comment by JaGeo** [comment]
Maybe an issue with the memory store?

**Comment by JaGeo** [comment]
Or could the gap outputs be an issue again. I have noticed that we again have the screen output about he parallelization

**Comment by JaGeo** [comment]
@naik-aakash !!!!!! Yes! I think it solved. It wad the screen output. 🥲

**Comment by naik-aakash** [comment]
> @naik-aakash !!!!!! Yes! I think it solved. It was the screen output or the parallelisation 🥲

Yes, setting OMP_NUM_THREADS globally for pytest was the solution. I also noticed when we used os module to do this , libomp complained with invalid value error. So problem was arising mainly from GAP 😄

**Comment by naik-aakash** [comment]
I will clean up bit of commented out lines and then will ping you so then it can be merged finally 🥳

**Review by JaGeo — APPROVED** [review]

**Pull request merged**
