### PR TITLE
Docs fixes

### PR DESCRIPTION
**Pull request by QuantumChemist**
some corrections, adjustments and fixes of the documentation
- [x] add more documentation on the choice of the fitting parameter for the phonon workflow. maybe, provide the Si choice as a default or explain how to chose it
- [x] add documentation on how to allow users to adapt VASP settings more easily

### CODE REVIEW

**Comment by QuantumChemist** [comment]
@JaGeo , here is the new PR.

If the issue with the stuck is fixed and you are happy with the changes, we can merge this PR.

**Comment by JaGeo** [comment]
I will merge once docs and linting are through. Then, we need to work on the tests

**Comment by QuantumChemist** [comment]
> I will merge once docs and linting are through. Then, we need to work on the tests

Ok, now everything except the stuck test has passed. And in principle test split 5 passes as well as one could see in recent CI runs.

**Comment by JaGeo** [comment]
There are some conflicts now. Could you resolve them, @QuantumChemist ?

**Comment by QuantumChemist** [comment]
> There are some conflicts now. Could you resolve them, @QuantumChemist ?

solved! :)

**Pull request merged**
