### PR TITLE
Include autoplex docker

### LINKED ISSUE #128: Include autoplex as part of Docker image after repository is made public.
Currently, image does not contain autoplex package as part of if, as we have not yet made the repository public. We can include it after it is made public

### PR DESCRIPTION
**Pull request by naik-aakash**
Closes #128

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi @JaGeo , this could be merged now

**Comment by JaGeo** [comment]
@naik-aakash tests are failing

**Comment by naik-aakash** [comment]
> @naik-aakash tests are failing

I had cancelled them. Trying to find the issue with test getting stuck. Tests are not failing due the changes in this PR

**Comment by JaGeo** [comment]
@naik-aakash i see

**Pull request merged**
