### PR TITLE
Update docker image - Include LAMMPS 

### PR DESCRIPTION
**Pull request by naik-aakash**
Hi @YuanbinLiu, Following up on your comment in PR #203 (https://github.com/autoatml/autoplex/pull/203#discussion_r1833806376), I have now tried to include LAMMPs in our CI workflow setup (lammps is compiled with PACE and python package). I tested whether the installation was working or not. It seems to run fine when I try to execute the examples from the source code. I mainly checked demo.py and mc.py (https://github.com/lammps/lammps/tree/develop/python/examples). 

These are commands used for compiling the lammps from source code in the docker image

```
# Install LAMMPS (rss)
RUN curl -fsSL https://download.lammps.org/tars/lammps.tar.gz -o /opt/lammps.tar.gz \
    && tar -xf /opt/lammps.tar.gz -C /opt \
    && rm /opt/lammps.tar.gz \
    && cd /opt/lammps-* \
    && mkdir build \
    && cd build \
    && cmake -D PKG_ML-PACE=yes -D PKG_PYTHON=on -D BUILD_LIB=on -D BUILD_SHARED_LIBS=on ../cmake \
    && cmake --build . \
    && make -j 4 install \
    && make install-python

# Add LAMMPS to PATH
ENV PATH="${PATH}:/root/.local/bin"
```

The compilation runs through successfully, and the `lmp` binary is accessible on the system `PATH`. Python package imports also work fine . So I have the following questions 
1) Is there any specific version of lammps you are using?
2) Do Any other flags need to be switched on when compiling? 
3) the current RSS test, in general, is not working with J-ACE and needs to be updated
4) Is there anything else that needs to be added to `LD_LIBRARY_PATH `or system `PATH`? 

Because enabling the commented-out test of J-ACE in the `tests/rss/test_rss.py` fails with a bunch of fatal Python errors. 

I see there are few lines commented out, here https://github.com/autoatml/autoplex/blob/e660c5c4d06d5bcdda47b49d7e8dbd0762f0df47/autoplex/data/rss/utils.py#L344 ? Is this the reason for failing tests as well?

# Todos

- [x] Restrict docker image publish workflows to run only on main repo after the lammps compilation flags are confirmed

### CODE REVIEW

**Comment by naik-aakash** [comment]
> Do you know if you need to build it with QUIP support? https://docs.lammps.org/Build_extras.html#ml-quip

I saw this, but as QUIP support was not mentioned, I did not enable that. But I think currently inferace with J-ACE is also not complete for RSS after looking at commented out lines

**Comment by JaGeo** [comment]
@naik-aakash should I merge it?

**Comment by naik-aakash** [comment]
> @naik-aakash should I merge it?

Not sure, if there are other flags to be added in lammps compilation. Better to wait for tomorrow ?

**Comment by JaGeo** [comment]
Yeah. Let's wait for conformation. Thanks anyway 😀

**Comment by JaGeo** [comment]
@YuanbinLiu Can you please help us with the flags needed for the lammps compilation? Then, we can also add a test for LAMMPS in #203 . Thanks!

**Review by JaGeo — APPROVED** [review]

**Comment by YuanbinLiu** [comment]
For the compilation, we need libpace.tar.gz. Here is my recipe on our HPC for compiling lammps-ace:

```
git clone -b release https://github.com/lammps/lammps
cd lammps
mkdir build
cd build
wget -O libpace.tar.gz https://github.com/wcwitt/lammps-user-pace/archive/main.tar.gz

cmake  -C ../cmake/presets/clang.cmake -D BUILD_SHARED_LIBS=on -D BUILD_MPI=yes \
-DMLIAP_ENABLE_PYTHON=yes -D PKG_PYTHON=on -D PKG_KOKKOS=yes -D Kokkos_ARCH_ZEN3=yes \
-D PKG_PHONON=yes -D PKG_MOLECULE=yes -D PKG_MANYBODY=yes \
-D Kokkos_ENABLE_OPENMP=yes -D BUILD_OMP=yes -D LAMMPS_EXCEPTIONS=yes -D PKG_ML-QUIP=yes \
-D QUIP_LIBRARY=/u/vld/applications/lammps-reqs/QUIP-lammps/build/linux_x86_64_gfortran/libquip.a \
-D PKG_ML-PACE=yes -D PACELIB_MD5=$(md5sum libpace.tar.gz | awk '{print $1}') \
-D PKG_SPIN=yes -D PKG_ML-SNAP=yes -D PKG_ML-IAP=yes -D CMAKE_INSTALL_PREFIX=$LAMMPS_INSTALL -D CMAKE_EXE_LINKER_FLAGS:STRING="-lgfortran" \
../cmake

make -j 16
make install-python
```

$LAMMPS_INSTALL is the conda environment for installing the lammps-python interface.

**Comment by YuanbinLiu** [comment]
If it still doesn't work, I would suggest commenting out this part for now. After the paper is sent out, we can revisit it later.

**Comment by naik-aakash** [comment]
Hi @YuanbinLiu, thanks for sharing the details, It seems a lot of other flags are added that are not enabled by default, 

But at this point, in the docker image, without including all the other flags you mentioned, I actually have the same output for the above-mentioned Python command to check if the installation is working. 

So, does it mean there are other dependencies in the flags you shared, or are they not really necessary?

**Comment by JaGeo** [comment]
@naik-aakash I guess those two are not required: `PKG_ML-QUIP=yes \
-D QUIP_LIBRARY=/u/vld/applications/lammps-reqs/QUIP-lammps/build/linux_x86_64_gfortran/libquip.a \`

**Comment by YuanbinLiu** [comment]
@naik-aakash have you included `-D PACELIB_MD5=$(md5sum libpace.tar.gz | awk '{print $1}')`? Without this, even if you have successfully installed lammps, it is for pacemaker-ace not julia-ace. We specifically need libpace.tar.gz for julia-ace.

**Comment by YuanbinLiu** [comment]
> @naik-aakash I guess those two are not required and cannot be enabled as we do not have these files: `PKG_ML-QUIP=yes \ -D QUIP_LIBRARY=/u/vld/applications/lammps-reqs/QUIP-lammps/build/linux_x86_64_gfortran/libquip.a \`

yes, we don't them

**Comment by naik-aakash** [comment]
> @naik-aakash have you included `-D PACELIB_MD5=$(md5sum libpace.tar.gz | awk '{print $1}')`? Without this, even if you have successfully installed lammps, it is for pacemaker-ace not julia-ace. We specifically need libpace.tar.gz for julia-ace.

Ah okay, will try to include it then. This could be missing

**Pull request merged**
